# Generated by Django 3.1.1 on 2021-03-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201114_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clientEmail',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiptNumber',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
