# Generated by Django 3.1.1 on 2021-03-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210303_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receiptNumber',
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
