# Generated by Django 3.1.1 on 2021-03-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210303_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='clientEmail',
        ),
    ]
