# Generated by Django 2.2.10 on 2020-04-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.CharField(max_length=40),
        ),
    ]
